### ISSUE TITLE
Trade GGx (Smart Contract Support)

### ISSUE THREAD

**Issue by xcthulhu** [ggxchain/ggxnode#229]
#### Description ####

Our smart contracts need to be able to trade the GGx gas token on GGx's DEX.

#### Definition of "Done" ####

Smart contract supports trading GGx token, complete with passing unit tests demonstrating the capability.

**Comment by akorchyn** [comment]
I think we should be able to trade our own token already, as it's listed as an asset. But if you mean gasless, then probably not and not really sure that it would be easy to do on backend.
